/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author verdy
 */
public class PengusahaBeranda extends javax.swing.JPanel {

    /**
     * Creates new form PengusahaBeranda
     */
    public PengusahaBeranda() {
        initComponents();
    }

    public JTable getTableLapak() {
        return tableLapak;
    }

    public void setTableLapak(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }
    
    public JButton btnBuka(){
        return btnBuka;
    }
    
    public JButton btnRefresh(){
        return btnRefresh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBeranda = new javax.swing.JPanel();
        tfSubJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLapak = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnBuka = new javax.swing.JButton();

        JPanelBeranda.setBackground(new java.awt.Color(247, 255, 246));
        JPanelBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfSubJudul.setText("Mencari Kerjasama");
        JPanelBeranda.add(tfSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        JPanelBeranda.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 540, 10));

        tableLapak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Komoditi", "Pemilik", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tableLapak);

        JPanelBeranda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 540, 360));

        btnRefresh.setText("Refresh");
        JPanelBeranda.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        btnBuka.setText("Buka");
        JPanelBeranda.add(btnBuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanelBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JPanelBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBeranda;
    private javax.swing.JButton btnBuka;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableLapak;
    private javax.swing.JLabel tfSubJudul;
    // End of variables declaration//GEN-END:variables
}
