/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MainController;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import model.UserModel;

/**
 *
 * @author HP
 */
public class Petani extends javax.swing.JFrame {

    int MouseX;
    int MouseY;
    GridBagLayout layout = new GridBagLayout();
    PetaniBeranda beranda;
    PetaniProfile profil;
    PetaniTbhKerjasama tbhKerjasama;
    PetaniDftrKerjasama dftrKerjasama;
    PetaniDftrTrx trx;
    PetaniVerif verif;

    public Petani(PetaniBeranda petaniBeranda, PetaniProfile petaniProfile,
            PetaniTbhKerjasama petaniTbhKerjasama, PetaniDftrKerjasama petaniDftrKerjasama,
            PetaniDftrTrx petaniDftrTrx, PetaniVerif petaniVerif) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.beranda = petaniBeranda;
        this.profil = petaniProfile;
        this.tbhKerjasama = petaniTbhKerjasama;
        this.dftrKerjasama = petaniDftrKerjasama;
        this.trx = petaniDftrTrx;
        this.verif = petaniVerif;

        panelPetani.setLayout(layout);
        panelPetani.add(beranda);
        panelPetani.add(profil);
        panelPetani.add(tbhKerjasama);
        panelPetani.add(dftrKerjasama);
        panelPetani.add(trx);
        panelPetani.add(verif);

        this.beranda.setVisible(true);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(false);
        this.verif.setVisible(false);

        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                UserModel m = new UserModel();
                Login vl = new Login();
                Daftar vd = new Daftar();
                Main vm = new Main(vl, vd);

                MainController c1 = new MainController(vd, m, vm);
                MainController c2 = new MainController(vl, m, vm);
                dispose();
            }
        });
    }

    public JLabel getNama_user() {
        return nama_user;
    }

    public void setNama_user(String nama_user) {
        this.nama_user.setText(nama_user);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama_user = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        btnTbh = new javax.swing.JButton();
        btnKerjasama = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelPetani = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnVerif = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 255, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8_gardener_48px.png"))); // NOI18N
        nama_user.setText("Petani Kebun");
        jPanel1.add(nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 840, 40));

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnBeranda.png"))); // NOI18N
        btnBeranda.setBorderPainted(false);
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnProfil.png"))); // NOI18N
        btnProfil.setBorderPainted(false);
        btnProfil.setContentAreaFilled(false);
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnTbh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnTambahKerjasama.png"))); // NOI18N
        btnTbh.setBorderPainted(false);
        btnTbh.setContentAreaFilled(false);
        btnTbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhActionPerformed(evt);
            }
        });
        jPanel1.add(btnTbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btnKerjasama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnDaftarkerjasama.png"))); // NOI18N
        btnKerjasama.setBorderPainted(false);
        btnKerjasama.setContentAreaFilled(false);
        btnKerjasama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKerjasamaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKerjasama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnLogout.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 70, 20));

        jLabel4.setText("Kerjasama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        panelPetani.setBackground(new java.awt.Color(247, 255, 246));
        panelPetani.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(panelPetani, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 660, 510));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/close.png"))); // NOI18N
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        btnVerif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnVerif.png"))); // NOI18N
        btnVerif.setBorderPainted(false);
        btnVerif.setContentAreaFilled(false);
        btnVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnDaftarTransaksi.png"))); // NOI18N
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX - MouseX, kordinatY - MouseY);
    }//GEN-LAST:event_jLabel10MouseDragged

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        MouseX = evt.getX();
        MouseY = evt.getY();
    }//GEN-LAST:event_jLabel10MousePressed

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        this.beranda.setVisible(true);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(false);
        this.verif.setVisible(false);
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        this.beranda.setVisible(false);
        this.profil.setVisible(true);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(false);
        this.verif.setVisible(false);
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnKerjasamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKerjasamaActionPerformed
        this.beranda.setVisible(false);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(true);
        this.trx.setVisible(false);
        this.verif.setVisible(false);
    }//GEN-LAST:event_btnKerjasamaActionPerformed

    private void btnTbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhActionPerformed
        this.beranda.setVisible(false);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(true);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(false);
        this.verif.setVisible(false);
    }//GEN-LAST:event_btnTbhActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifActionPerformed
        this.beranda.setVisible(false);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(false);
        this.verif.setVisible(true);
    }//GEN-LAST:event_btnVerifActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        this.beranda.setVisible(false);
        this.profil.setVisible(false);
        this.tbhKerjasama.setVisible(false);
        this.dftrKerjasama.setVisible(false);
        this.trx.setVisible(true);
        this.verif.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petani(beranda, profil, tbhKerjasama, dftrKerjasama, trx, verif)
                        .setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnKerjasama;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnTbh;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnVerif;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama_user;
    private javax.swing.JPanel panelPetani;
    // End of variables declaration//GEN-END:variables
}
