/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author verdy
 */
public class PetaniTbhKerjasama extends javax.swing.JPanel {

    /**
     * Creates new form PetaniTbhKerjasama
     */

    public PetaniTbhKerjasama() {
        initComponents();
    }

    public JButton btnSelesai() {
        return btnSelesai;
    }

    public JComboBox<String> getCbUnit() {
        return cbUnit;
    }

    public JTextArea getDeskripsi() {
        return deskripsi;
    }

    public String setDeskripsi(String deskripsi) {
        return deskripsi;
    }

    public JButton btnUnggah() {
        return btnUnggah;
    }

    public JLabel image() {
        return image;
    }

    public JTextField getJudul() {
        return judul;
    }

    public String setJudul(String judul) {
        return judul;
    }

    public JTextField getKebutuhan() {
        return kebutuhan;
    }

    public int setKebutuhan(int kebutuhan) {
        return kebutuhan;
    }

    public JTextField getKomoditi() {
        return komoditi;
    }

    public String setKomoditi(String komoditi) {
        return komoditi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfSubJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        komoditi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        kebutuhan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        cbUnit = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();
        btnUnggah = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(247, 255, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfSubJudul.setText("Tambah kerjasama");
        jPanel2.add(tfSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, 10));

        jLabel1.setText("Judul");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, -1));

        jLabel3.setText("Foto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, -1));

        judul.setBorder(null);
        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });
        jPanel2.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 390, 20));

        komoditi.setBorder(null);
        komoditi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komoditiActionPerformed(evt);
            }
        });
        jPanel2.add(komoditi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 390, 20));

        jLabel5.setText("Komoditi");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, -1));

        jLabel7.setText("Deksripsi");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, -1));

        deskripsi.setColumns(20);
        deskripsi.setRows(5);
        deskripsi.setBorder(null);
        jScrollPane1.setViewportView(deskripsi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 390, 100));

        jLabel8.setText("Kebutuhan (Stock)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        kebutuhan.setBorder(null);
        kebutuhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebutuhanActionPerformed(evt);
            }
        });
        jPanel2.add(kebutuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 230, 20));

        jLabel9.setText("Unit");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, -1));

        btnSelesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/btnSelesai.png"))); // NOI18N
        btnSelesai.setBorderPainted(false);
        btnSelesai.setContentAreaFilled(false);
        jPanel2.add(btnSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 110, 30));

        cbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ton", "kwintal", "kg" }));
        jPanel2.add(cbUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 140, -1));
        jPanel2.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 250, 100));

        btnUnggah.setText("Unggah");
        jPanel2.add(btnUnggah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void komoditiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komoditiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_komoditiActionPerformed

    private void kebutuhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebutuhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebutuhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnUnggah;
    private javax.swing.JComboBox<String> cbUnit;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField kebutuhan;
    private javax.swing.JTextField komoditi;
    private javax.swing.JLabel tfSubJudul;
    // End of variables declaration//GEN-END:variables
}
