/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author verdy
 */
public class PetaniVerif extends javax.swing.JPanel {

    /**
     * Creates new form PetaniPesan
     */
    public PetaniVerif() {
        initComponents();
    }
    public JTable getTable_verif() {
        return tblVerif;
    }

    public JButton btnVerif() {
        return btnVerif;
    }

    public void setTable_verif(DefaultTableModel tabel) {
        this.tblVerif.setModel(tabel);
    }

    public void setTabel(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }

    public JLabel getLapak() {
        return labelLapak;
    }

    public void setLapak(String lapak) {
        this.labelLapak.setText(lapak);
    }

    public JLabel getNama() {
        return labelNama;
    }

    public void setNama(String nama) {
        this.labelNama.setText(nama);
    }

    public JLabel getStatus() {
        return labelStatus;
    }

    public void setStatus(String status) {
        this.labelStatus.setText(status);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfSubJudul = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerif = new javax.swing.JTable();
        btnVerif = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelLapak = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(247, 255, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfSubJudul.setText("Pesan Masuk");
        jPanel2.add(tfSubJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 540, 10));

        tblVerif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lapak", "Nama", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVerif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVerifMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVerif);
        if (tblVerif.getColumnModel().getColumnCount() > 0) {
            tblVerif.getColumnModel().getColumn(1).setResizable(false);
            tblVerif.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 540, 370));

        btnVerif.setText("Verifikasi");
        jPanel2.add(btnVerif, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        labelNama.setText("jLabel1");
        jPanel2.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        labelLapak.setText("jLabel2");
        jPanel2.add(labelLapak, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        labelStatus.setText("jLabel3");
        jPanel2.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVerifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVerifMouseClicked
        int row = tblVerif.getSelectedRow();
        setNama(tblVerif.getModel().getValueAt(row, 0).toString());
        setLapak(tblVerif.getModel().getValueAt(row, 1).toString());
        setStatus(tblVerif.getModel().getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblVerifMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerif;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelLapak;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTable tblVerif;
    private javax.swing.JLabel tfSubJudul;
    // End of variables declaration//GEN-END:variables
}
